config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root "homes#top"

  post "/users/create",to:"users#create" 
  get "/users/account",to:"users#account"
  get "/users/account/edit",to:"users#account_edit"
  patch "/users/account/update",to:"users#account_update"
  get "/users/profile",to:"users#profile"
  get "/users/profile/edit",to:"users#profile_edit" 
  patch "/users/profile/update",to:"users#profile_update"
  delete "/users/:id/destroy",to:"users#destroy"
  

  get "/users/sign_in",to:"devise/sessions#new"
  post "/users/sign_in",to:"evise/sessions#create"
  delete "/users/sign_out",to:"devise/sessions#destroy"
  get "/users/password/new",to:"devise/passwords#new"
  get "/users/password/edit",to:"devise/passwords#edit"
  patch "/users/password",to:"devise/passwords#update"
  put "/users/password",to:"devise/passwords#update"
  post "/users/password",to:"devise/passwords#create"
  get "/users/cancel",to:"devise/registrations#cancel"
  get "/users/sign_up",to:"devise/registrations#new"
  get "/users/edit",to:"devise/registrations#edit"
  
  patch "/users",to:"devise/registrations#update"
  put "/users",to:"devise/registrations#update"
  delete "/users",to:"devise/registrations#destroy"
  post "/users",to:"devise/registrations#create"
  get "/users/sign_up",to: "devise/registrations#new"
  get 'users/account'
  
  
  get 'rooms/index',to:"rooms#index"
  get "/rooms/new",to:"rooms#new"
  post "/rooms/create",to:"rooms#create"
  get "/rooms/:id/edit",to:"rooms#edit"
  get "/rooms/:id/show",to:"rooms#show"
  patch "/rooms/:id/update",to:"rooms#update"
  delete "/rooms/:id/destroy",to:"rooms#destroy"
  get "/rooms/search",to:"rooms#search"

  get 'reservations/index'
  get "reservations/new",to:"reservations#new"
  get "reservations/confirm",to:"reservations#confirm"
  post "reservations/create",to:"reservations#create"
  get "reservations/:id/rebook",to:"reservations#rebook"
  get "reservations/:id/rebook_confirm",to:"reservations#rebook_confirm"
  patch "/reservations/:id/update",to:"reservations#update"
  delete "/reservations/:id/destroy",to:"reservations#destroy"


  resources :users
  resources :rooms
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    has_many :rooms
    validates :check_in_date, presence: true
    validates :check_out_date, presence: true
    validates :number_of_people, presence: true, numericality: {only_integer: true, greater_than: 0}
    validate :check_in_date_check
    validate :check_out_date_check

    private
    def check_in_date_check
        if check_in_date && check_in_date < Date.current
            errors.add(:check_in_date, "は今日より後の日付を選択してください")
        end
    end

    def check_out_date_check
        if check_in_date && check_out_date && check_out_date <= check_in_date
            errors.add(:check_out_date, "はチェックイン日より後の日付を選択してください")
        end
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController


  def index
    @user = current_user
    @reservations = Reservation.where(user_id: @user.id)
  end

  def confirm
    @user = current_user
    @reservation = Reservation.new(params.require(:reservation).permit(:room_name, :room_introduction, :room_image , :price, :address, :check_in_date, :check_out_date, :number_of_people,:stay_days, :payment_amount, :user_id, :room_id))
    @day = Date.current
    if @reservation.invalid?
      @room = @reservation
      if @room.room_image.include?("default")
        @room.room_image = nil
      end
      render "rooms/show"
    else
      @reservation.stay_days = (@reservation.check_out_date - @day) - (@reservation.check_in_date - @day)
      @reservation.payment_amount = @reservation.price * @reservation.number_of_people * @reservation.stay_days
    end

  end

  def create
    @user = current_user
    @reservation = Reservation.new(params.require(:reservation).permit(:room_name, :room_introduction, :price, :address, :room_image, :check_in_date, :check_out_date, :number_of_people,:stay_days, :payment_amount, :user_id, :room_id))
    if @reservation.save
      redirect_to "/reservations/index"
    else
      render "confirm"
    end
  end

  def rebook
    @user = current_user
    @reservation = Reservation.find(params[:id])
  end

  def rebook_confirm
    @user = current_user
    @reservation = Reservation.new(params.require(:reservation).permit(:id, :room_name, :room_introduction, :price, :address, :room_image, :check_in_date, :check_out_date, :number_of_people,:stay_days, :payment_amount, :user_id, :room_id))
    @day = Date.current
    if @reservation.invalid?
      @room = @reservation
      render "rebook"
    else
      @reservation.stay_days = (@reservation.check_out_date - @day) - (@reservation.check_in_date - @day).to_i
      @reservation.payment_amount = @reservation.price * @reservation.number_of_people * @reservation.stay_days
    end
  end

  def update
    @user = current_user
    @reservation = Reservation.find(params[:id])
    if @reservation.update(params.require(:reservation).permit(:id, :room_name, :room_introduction, :price, :address, :room_image, :check_in_date, :check_out_date, :number_of_people,:stay_days, :payment_amount, :user_id, :room_id))
      redirect_to reservations_index_path
    else
      render "index"      
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_index_path
  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/confirm.html.erb
<h3>予約確認画面</h3>
<%= form_with  model: @reservation ,url: reservations_create_path, html: {multipart: true} ,method: :post,local: true do |f| %> 
  <thead>
      <tr>
        <th>チェックイン</th>
          <td><%= @reservation.check_in_date.strftime("%Y/%m/%d") %></td><br>
          <%= f.hidden_field :check_in_date, value: @reservation.check_in_date %>
        <th>チェックアウト</th>
          <td><%= @reservation.check_out_date.strftime("%Y/%m/%d") %></td><br>
          <%= f.hidden_field :check_out_date, value: @reservation.check_out_date %>
        <th>宿泊日数</th>
          <td><%="#{@reservation.stay_days}日" %></td><br>
          <%= f.hidden_field :stay_days, value: @reservation.stay_days %>
        <th>宿泊人数</th>
          <td><%= "#{@reservation.number_of_people}人" %></td><br>
          <%= f.hidden_field :number_of_people, value: @reservation.number_of_people %>
        <th>お支払い金額</th>
          <td><%= "#{@reservation.payment_amount.to_s(:delimited, delimiter: ',')}円" %></td><br>
          <%= f.hidden_field :payment_amount, value: @reservation.payment_amount %>
        <div class="field">
          <%= f.hidden_field :user_id,value: @reservation.user_id %>        
          <%= f.hidden_field :room_id,value: @reservation.room_id %>
          <%= f.hidden_field :room_name,value: @reservation.room_name %>
          <%= f.hidden_field :room_introduction,value: @reservation.room_introduction %>
          <%= f.hidden_field :price,value: @reservation.price %>        
          <%= f.hidden_field :address,value: @reservation.address %>
          <%= f.hidden_field :room_image,value: @reservation.room_image %>
        </div> 
        <div class="field confirm_submit">
          <%= f.submit "予約を確定する", class: "confirm_submit"%>
        </div>  
      </tr>
  </thead>
<% end %>

app/views/reservations/index.html.erb
<h3>予約済み一覧</h3>
<table>
  <thead>
    <tr>
      <th>イメージ</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>合計料金</th>
      <th>チェックイン</th>
      <th>チェックアウト</th>
      <th>予約確定日時</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td>
          <% if reservation.room_image.blank? %>
            <%= image_tag "default_room.png" , class:"image" %><br>   
          <% else %>
            <img src=<%= reservation.room_image %> class="image"><br>   
          <% end %>  
        </td>
        <td><%= link_to "#{reservation.room_name}", "/rooms/#{reservation.room_id}/show" , class:"link" %></td>
        <td class="reservations_introduction">
          <%= reservation.room_introduction %>
        </td>
        <td><%= "¥#{reservation.payment_amount.to_s(:delimited, delimiter: ',')}" %></td>
        <td><%= reservation.check_in_date.strftime("%Y/%m/%d") %></td>
        <td><%= reservation.check_out_date.strftime("%Y/%m/%d") %></td>
        <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
        <td><%= link_to "再予約","/reservations/#{reservation.id}/rebook" , class:"link" %></td>
        <td><%= button_to "削除","/reservations/#{reservation.id}/destroy", method: :delete, class: "delete_button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reservations/rebook.html.erb
<h3>再予約</h3>
<%= render "shared/error", obj: @reservation %> 
<%= form_with  model: @reservation ,url: "/reservations/#{@reservation.id}/rebook_confirm", html: {multipart: true} ,method: :get,local: true do |f| %>  
    <div class="field room_detail">
        <td>
            <% if @reservation.room_image.blank? %>
                <%= image_tag "default_room.png" %>
            <% else %>
                <img src=<%= @reservation.room_image %> class="room_image"><br>   
            <% end %>       
        </td>
    </div>
    <div class="room_information">
        <div class="field">
            <td><%= @reservation.room_name %></td>
            <td><%= f.hidden_field :room_name,value: @reservation.room_name %></td>
        </div>
        <div class="field"> 
            <td><%= @reservation.address %></td>
            <td><%= f.hidden_field :address,value: @reservation.address %></td>
        </div>
        <div class="field">
            <td><%= f.label :"¥#{@reservation.price.to_s(:delimited, delimiter: ',')}" %></td>
            <td><%= f.hidden_field :price,value: @reservation.price %></td>
        </div>
        <div class="field">
            <td><%= @reservation.room_introduction %></td>
            <td><%= f.hidden_field :room_introduction,value: @reservation.room_introduction %></td>
        </div>
        <div class="field">
            <td><%= f.label :チェックイン %></td><p class="caution">※必須</p><br> 
            <td><%= f.date_field :check_in_date %></td>
            <p class="caution"><%= @check_in_date_caution %></p>
        </div>
        <div class="field">
            <td><%= f.label :チェックアウト %></td><p class="caution">※必須</p><br> 
            <td><%= f.date_field :check_out_date %></td>
            <p class="caution"><%= @check_out_date_caution %></p>
        </div>
        <div class="field">
            <td><%= f.label :人数 %></td><p class="caution">※必須</p><br> 
            <td><%= f.text_field :number_of_people %></td>
        </div>
        <div class="field">     
            <%= f.hidden_field :user_id,value: @reservation.user_id %> 
            <%= f.hidden_field :id,value: @reservation.id %> 
            <%= f.hidden_field :room_image,value: @reservation.room_image %>
            <% if @reservation.room_id %>
                <%= f.hidden_field :room_id,value: @reservation.room_id %>
            <% else %>
                <%= f.hidden_field :room_id,value: @room.room_id %>
            <% end %>        
        </div>
        <div class="field">
            <%= f.submit "再予約する", class: "submit_button"%>
        </div>
    </div>
<% end %>




   

app/views/reservations/rebook_confirm.html.erb
<h3>再予約確認画面</h3>
<%= form_with  model: @reservation ,url: "/reservations/#{@reservation.id}/update", html: {multipart: true} ,method: :patch,local: true do |f| %> 
  <thead>
    <tr>
      <th>チェックイン</th>
        <td><%= @reservation.check_in_date.strftime("%Y/%m/%d") %></td><br>
        <%= f.hidden_field :check_in_date, value: @reservation.check_in_date %>
      <th>チェックアウト</th>
        <td><%= @reservation.check_out_date.strftime("%Y/%m/%d") %></td><br>
        <%= f.hidden_field :check_out_date, value: @reservation.check_out_date %>
      <th>宿泊日数</th>
        <td><%="#{@reservation.stay_days}日" %></td><br>
        <%= f.hidden_field :stay_days, value: @reservation.stay_days %>
      <th>宿泊人数</th>
        <td><%= "#{@reservation.number_of_people}人" %></td><br>
        <%= f.hidden_field :number_of_people, value: @reservation.number_of_people %>
      <th>お支払い金額</th>
        <td><%= "#{@reservation.payment_amount.to_s(:delimited, delimiter: ',')}円" %></td><br>
        <%= f.hidden_field :payment_amount, value: @reservation.payment_amount %>
      <div class="field">
        <%= f.hidden_field :user_id,value: @reservation.user_id %>        
        <%= f.hidden_field :room_id,value: @reservation.room_id %>
        <%= f.hidden_field :room_name,value: @reservation.room_name %>
        <%= f.hidden_field :room_introduction,value: @reservation.room_introduction %>
        <%= f.hidden_field :price,value: @reservation.price %>        
        <%= f.hidden_field :address,value: @reservation.address %>
        <%= f.hidden_field :room_image,value: @reservation.room_image %>
      </div> 
      <div class="field">
        <%= f.submit "再予約を確定する", class: "confirm_submit"%>
      </div>  
    </tr>
  </thead>
<% end %>