config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root "homes#top"

  post "/users/create",to:"users#create" 
  get "/users/account",to:"users#account"
  get "/users/account/edit",to:"users#account_edit"
  patch "/users/account/update",to:"users#account_update"
  get "/users/profile",to:"users#profile"
  get "/users/profile/edit",to:"users#profile_edit" 
  patch "/users/profile/update",to:"users#profile_update"
  delete "/users/:id/destroy",to:"users#destroy"
  

  get "/users/sign_in",to:"devise/sessions#new"
  post "/users/sign_in",to:"evise/sessions#create"
  delete "/users/sign_out",to:"devise/sessions#destroy"
  get "/users/password/new",to:"devise/passwords#new"
  get "/users/password/edit",to:"devise/passwords#edit"
  patch "/users/password",to:"devise/passwords#update"
  put "/users/password",to:"devise/passwords#update"
  post "/users/password",to:"devise/passwords#create"
  get "/users/cancel",to:"devise/registrations#cancel"
  get "/users/sign_up",to:"devise/registrations#new"
  get "/users/edit",to:"devise/registrations#edit"
  
  patch "/users",to:"devise/registrations#update"
  put "/users",to:"devise/registrations#update"
  delete "/users",to:"devise/registrations#destroy"
  post "/users",to:"devise/registrations#create"
  get "/users/sign_up",to: "devise/registrations#new"
  get 'users/account'
  
  
  get 'rooms/index',to:"rooms#index"
  get "/rooms/new",to:"rooms#new"
  post "/rooms/create",to:"rooms#create"
  get "/rooms/:id/edit",to:"rooms#edit"
  get "/rooms/:id/show",to:"rooms#show"
  patch "/rooms/:id/update",to:"rooms#update"
  delete "/rooms/:id/destroy",to:"rooms#destroy"
  get "/rooms/search",to:"rooms#search"

  get 'reservations/index'
  get "reservations/new",to:"reservations#new"
  get "reservations/confirm",to:"reservations#confirm"
  post "reservations/create",to:"reservations#create"
  get "reservations/:id/rebook",to:"reservations#rebook"
  get "reservations/:id/rebook_confirm",to:"reservations#rebook_confirm"
  patch "/reservations/:id/update",to:"reservations#update"
  delete "/reservations/:id/destroy",to:"reservations#destroy"


  resources :users
  resources :rooms
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    mount_uploader :room_image, ImageUploader 
    belongs_to :user
    validates :room_name, presence: true
    validates :room_introduction, presence: true
    validates :price, presence: true, numericality: {only_integer: true, greater_than: 0}
    validates :address, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @user = current_user
    @rooms = Room.where(user_id: @user.id)
  end

  def new
    @user = current_user
    @room = Room.new
  end

  def create
    @user = current_user
    @room = Room.new(params.require(:room).permit(:room_name, :room_introduction, :price, :address, :room_image, :user_id))
    if @room.save
      redirect_to "/rooms/index"
    else
      render "new"
    end
  end

  def edit
    @user = current_user
    @room = Room.find(params[:id])
  end 

  def show
    @user = current_user
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to "/rooms/index"
  end

  def update
    @user = current_user
    @room = Room.find(params[:id])
    if @room.update(params.require(:room).permit(:room_name, :room_introduction, :price, :address, :room_image))
      redirect_to "/rooms/index"
    else
      render "edit"      
    end
  end

  def search
    @user = current_user
    @rooms = Room.where("address like ?", "%#{params[:area_name]}%").where("room_name like ? or room_introduction like ?", "%#{params[:keyword]}%","%#{params[:keyword]}%")
    @count = @rooms.count
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<h1>施設情報の編集</h1>
<%= render "shared/error", obj: @room %> 
<%= form_with model: @room, url: {action: "update"} , html: {multipart: true} ,local: true do |f| %>

  <div class="field">
    <%= f.label :施設名 %><br />
    <%= f.text_field :room_name, autofocus: true, autocomplete: "room_name" %><br />
  </div>

  <div class="field">
    <%= f.label :施設詳細 %><br />
    <%= f.text_field :room_introduction, autocomplete: "room_introduction" %><br />
  </div>

  <div class="field">
    <%= f.label :料金 %><br />
    <%= f.text_field :price, autocomplete: "price"%>
  </div>  

  <div class="field">
    <%= f.label :住所 %><br />
    <%= f.text_field :address, autocomplete: "address"%>
  </div>  

  <div class="field">
    <%= f.label :施設画像 %><br />
    <%= f.file_field :room_image, autocomplete: "room_image"%>
  </div>  

  <div class="field"><br />
    <%= f.submit :room_image, value: "更新"%>
  </div>
<% end %> 

<%=link_to("/") do %>
<button class="btn" >キャンセル</button>
<%end%><br>

<%= link_to "Back", :back %>

app/views/rooms/index.html.erb
<h3>登録済み一覧</h3>
<table>
  <thead>
    <tr>
      <th>イメージ</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td>
          <% if room.room_image.blank? %>
            <%= image_tag "default_room.png" , class:"image" %><br>   
          <% else %>
            <img src=<%= room.room_image %> class="image"><br>   
          <% end %>  
        </td>
        <td><%= link_to "#{room.room_name}", "/rooms/#{room.id}/show", class:"link" %></td>
        <td class="introduction"> 
          <%= room.room_introduction %>
        </td>
        <td><%= "¥#{room.price.to_s(:delimited, delimiter: ',')}" %></td>
        <td><%= room.created_at.strftime("%Y/%m/%d") %></td>
        <td><%= link_to "編集", "/rooms/#{room.id}/edit" , class:"link" %></td>
        <td><%= button_to "削除", "/rooms/#{room.id}/destroy", method: :delete , class: "delete_button"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/new.html.erb
<h1>新規登録（施設）</h1>

<%= render "shared/error", obj: @room %> 

<%= form_with model: @room, url: rooms_create_path, html: {multipart: true} ,local: true do |f| %>

  <div class="field">
    <%= f.label :施設名 %><p class="caution">※必須</p><br>
    <%= f.text_field :room_name, autofocus: true, autocomplete: "room_name" %><br />
  </div>

  <div class="field">
    <%= f.label :施設詳細 %><p class="caution">※必須</p><br>
    <%= f.text_field :room_introduction, autocomplete: "room_detail" %><br />
  </div>

  <div class="field">
    <%= f.label :料金 %><p class="caution">※必須</p><br>
    <%= f.text_field :price, autocomplete: "price"%>
  </div>  

  <div class="field">
    <%= f.label :住所 %><p class="caution">※必須</p><br>
    <%= f.text_field :address, autocomplete: "address"%>
  </div>  

  <div class="field">
    <%= f.label :施設画像 %>
    <%= f.file_field :room_image, autocomplete: "room_image"%>
  </div>  

  <%= f.hidden_field :user_id ,value: @user.id %>

  <div class="actions">
    <%= f.submit "保存"%>
  </div>  
<% end %> 

<%=link_to("/") do %>
<button class="btn" >キャンセル</button>
<%end%><br>

app/views/rooms/search.html.erb
<div class="rooms_search">
  <%= form_with  url: rooms_search_path, html: {multipart: true} ,method: :get, local: true do |f| %> 
      <%= f.text_field :area_name, placeholder: "エリアを入力してください" %>
      <%= f.text_field :keyword, placeholder: "キーワードを入力してください" %>
      <%= f.submit "検索" %>
  <% end %>
</div>
<h3><%= "#{@count}件が見つかりました。" %></h3>
<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>料金</th>
      <th>住所</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td>
          <% if room.room_image.blank? %>
            <%= image_tag "default_room.png" , class:"image" %><br>   
          <% else %>
            <img src=<%= room.room_image %> class="image"><br>   
          <% end %>  
        </td>
        <td><%= room.room_name %></td>
        <td class="introduction">
          <%= room.room_introduction %>
        </td>
        <td><%= "¥#{room.price.to_s(:delimited, delimiter: ',')}" %></td>
        <td><%= room.address %></td>
        <td><%= link_to "詳細","/rooms/#{room.id}/show" , class:"link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/show.html.erb
<h3>部屋詳細</h3>
<%= render "shared/error", obj: @reservation %> 
<%= form_with  model: Reservation.new ,url: reservations_confirm_path, html: {multipart: true} ,method: :get,local: true do |f| %>  
    <div class="field room_detail">
        <td>
            <% if @room.room_image.blank? %>
                <%= image_tag "default_room.png" %>
            <% else @room.room_image %>   
                <img src=<%= @room.room_image %> class="room_image">
            <% end %>       
        </td>
    </div>
    <div class="room_information">
        <div class="field">
            <td><%= @room.room_name %></td>
            <td><%= f.hidden_field :room_name,value: @room.room_name %></td>
        </div>
        <div class="field"> 
            <td><%= @room.address %></td>
            <td><%= f.hidden_field :address,value: @room.address %></td>
        </div>
        <div class="field">
            <td><%= f.label :"¥#{@room.price.to_s(:delimited, delimiter: ',')}" %></td>
            <td><%= f.hidden_field :price,value: @room.price %></td>
        </div>
        <div class="field">
            <td><%= @room.room_introduction %></td>
            <td><%= f.hidden_field :room_introduction,value: @room.room_introduction %></td>
        </div>
        <div class="field">
            <td><%= f.label :チェックイン %></td><p class="caution">※必須</p><br> 
            <td><%= f.date_field :check_in_date,value: @reservation.check_in_date  %></td>
            <p class="caution"><%= @check_in_date_caution %></p>
        </div>
        <div class="field">
            <td><%= f.label :チェックアウト %></td><p class="caution">※必須</p><br> 
            <td><%= f.date_field :check_out_date,value: @reservation.check_out_date %></td>
            <p class="caution"><%= @check_out_date_caution %></p>
        </div>
        <div class="field">
            <td><%= f.label :人数 %></td><p class="caution">※必須</p><br> 
            <td><%= f.text_field :number_of_people,value: @reservation.number_of_people %></td>
            <p class="caution"><%= @number_of_people_caution %></p>
        </div>
        <div class="field">       
            <%= f.hidden_field :user_id,value: @user.id %>
            <%= f.hidden_field :room_image,value: @room.room_image %>
            <% if @room.id %>
                <%= f.hidden_field :room_id,value: @room.id %> 
            <% elsif @room.room_id %>
                <%= f.hidden_field :room_id,value: @room.room_id %> 
            <%  end %>
        </div>
        <div class="field">
            <%= f.submit "予約する", class: "submit_button"%>
            <%= link_to "戻る", :back %>
        </div>
    </div>
<% end %>



   